spring:
  application:
    name: toolserve
  profiles:
    active: dev

  rabbitmq:
    host: 47.120.11.197 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
