spring:
  application:
    name: toolserve
  profiles:
    active: dev

  rabbitmq:
    host: 47.120.11.197 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

#系统的整体配置
# 后续可以把配置写在一个jar里面，利用springboot机制来提供yml的属性配置提示
toolserver:
  author: larry
  rabbitmqEnabled: true


#google访问相关
google:
  client:
    # Google Drive新建的应用获取
    client-id: 663018976908-ttr6qsb6k7t8s2742no14iob1eluv7pu.apps.googleusercontent.com
    # Google Drive新建的应用获取
    client-secret:
    # OAuth 2.0授权流程中用于接收授权码的回调URI。用户完成授权后，Google会重定向到这个URI，并附上一个授权码
    redirect-uri: http://127.0.0.1:8081/googledrive/redirectUri
    # 指定此授权范围是访问Google Drive的权限
    scopes: https://www.googleapis.com/auth/drive.file
    needProxy: true

onedrive:
  client:
    # onedrive新建的应用获取
    client-id: YOUR_CLIENT_ID
    # onedrive新建的应用获取
    client-secret: YOUR_CLIENT_SECRET
    # OAuth 2.0授权流程中用于接收授权码的回调URI。用户完成授权后，Google会重定向到这个URI，并附上一个授权码
    redirect-uri: http://127.0.0.1:8081/oauth/callback
    # 租户id
    tenantId: cc143140-bdab-4c5a-9a90-129fa198920a

sharepoint:
  client:
    # sharepoint新建的应用获取
    client-id: YOUR_CLIENT_ID
    # sharepoint新建的应用获取
    client-secret: YOUR_CLIENT_SECRET
    # OAuth 2.0授权流程中用于接收授权码的回调URI。用户完成授权后，Google会重定向到这个URI，并附上一个授权码
    redirect-uri: http://127.0.0.1:8081/sharepoint/redirectUri
